Fix webpack/typescript require error.
Place Node/CommonJS exports before AMD exports to prevent the following error, which appears when using Webpack/TypeScript:
Uncaught TypeError: __webpack_require__.i(...) is not a function